{
    'name': 'Vehicle Master',
    'version': '17.0.1.0.0',
    'category': 'Services/Vehicle',
    'summary': 'Vehicle Master Application',
    'description': """Vehicle Master Application""",
    'author': 'Harman',
    'sequence': 1,
    'depends': ['base', 'product', 'stock', 'repair','mail', 'hr'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/vehicle_master.xml',
        'views/equipment_master_view.xml',
        'views/repair.xml',
        'views/repair_order_extra_cost_wizard_view.xml',
        'views/repair_order_grouped_by_vehicle.xml',
        'views/inventory_stock_view.xml',
        'views/product_issue.xml',
        'views/vehicle_repair_report_views.xml',
        'views/product_issue_report.xml',
        'views/stock_picking.xml',
        'views/repair_job_card_report.xml',
        'views/repair_card_report.xml',
        'data/sequence.xml',
        'views/workshop_master_view.xml',
        'views/product_template.xml',
        'views/job_card_summary_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
